name: poster
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  fluttertoast: ^8.2.4
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.0.9
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  pinput: ^5.0.1
  carousel_slider: ^5.0.0
  permission_handler: ^11.4.0
  logger: ^2.5.0
  screenshot: ^3.0.0
  photo_manager: ^3.6.4
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  video_player: ^2.9.5
  chewie: ^1.5.0
  shimmer: ^3.0.0
  video_compress: ^3.1.0
  image: ^4.5.4
  lottie: ^3.3.1
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  ffmpeg_kit_min_gpl: ^6.0.3+2-LTS
  flutter_image_compress: ^2.4.0
  change_app_package_name: ^1.1.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.7
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Ramabhadra
      fonts:
        - asset: assets/Ramabhadra-Regular.ttf
          weight: 400

  assets:
    - assets/
    - assets/Ramabhadra-Regular.ttf
    - assets/images/
    - assets/lottie/success.json

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/app_icon.png"
#  adaptive_icon_background: "#BBDEFB" # Light Blue
#
## âœ… Splash screen configuration
#flutter_native_splash:
#  color: "#BBDEFB" # Light Blue for all platforms
#  image: "assets/app_icon.png"
#  android: true
#  ios: true
#  web: false
#  android_12:
#    color: "#BBDEFB" # Light Blue for Android 12 too
#    image: "assets/app_icon.png"
#    icon_background_color: "#BBDEFB"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image: null
  adaptive_icon_background: "#BBDEFB"

# Splash screen configuration
flutter_native_splash:
  color: "#FF0000"  # ðŸ”´ Red background
  android: true
  ios: true
  web: false
  image: null   # ðŸ‘ˆ shows on Android â‰¤ 11 + iOS

  android_12:
    color: "#FF0000"                  # ðŸ”´ Red background for Android 12+
    icon_background_color: "#FF0000"  # ðŸ”´ Must match background
    image: null        # ðŸ‘ˆ force logo on Android 12+

